Adding tags associated with a task
singer-io/tap-asana pull request #3
Opened 2019-09-06 17:47 UTC by dpick

This adds the tags field on tasks to the pull.

2019-09-06 17:47 UTC, cmerrick commented
Hi @dpick, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

2019-09-06 17:48 UTC, cmerrick commented
You did it @dpick!

Thank you for signing the Singer Contribution License Agreement.

2019-11-18 00:17 UTC, DenGrishin commented
Hey guys, 
Could you please review these changes. 
We found it very helpful.
Thank you.

2020-01-03 14:48 UTC, MattBurlew commented
This would be super helpful for us as well.

2020-01-10 20:52 UTC, alefgoto commented
This is very helpful, please, review it.

2020-02-04 20:59 UTC, jacobrobertbaca requested changes

2020-02-04 20:59 UTC, jacobrobertbaca commented on tap_asana/schemas/tasks.json
> +      ],
It's unclear what the schema is for the entries in the array?  Take a look at #7 to see what the addition of an array field should look like -- you need to specify the schema of the items in the array.

Also, this is missing a closing curly brace for the `tags` field

2020-02-05 16:25 UTC, nick-mccoy commented
We incorporated this change into #10.  Closing this

2020-02-05 16:25 UTC, closed without merging