Tdl 15272 fix bug in refresh token logic
singer-io/tap-asana pull request #41
Opened 2021-09-27 05:29 UTC by savan-chovatiya

# Description of change
(write a short description or paste a link to JIRA)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-10-08 06:44 UTC, savan-chovatiya commented on tap_asana/streams/base.py
> +                          max_tries=MAX_RETRIES)
Added max_tries limit as same as other exceptions because by default no limit on it so it may end up in a long loop.

2021-10-08 06:48 UTC, savan-chovatiya commented on tap_asana/asana.py
> -      return
Removed above condition because this function is only called when the access token expires so no need to return directly without a refreshing token.

2021-10-08 11:11 UTC, dbshah1212 approved these changes

2021-10-08 11:13 UTC, dbshah1212 requested changes
Why build is failing, please fix it, else looks good.

2021-10-11 10:31 UTC, savan-chovatiya commented on tap_asana/streams/base.py
> +        return data
`fn.find_all` is a function of the `asana` library that returns the generator so it will throw an error at a time of iteration over it. Due to this exceptions can't be thrown from the `call_api()` function so no error handling is utilized.
Changed generator to list above so it will throw an exception in that line only and exception handling will be utilized when required.

2021-10-29 06:49 UTC, dbshah1212 commented on tap_asana/streams/base.py
> +        return data
Please add this in a code comment

2021-10-29 06:50 UTC, dbshah1212 commented on tap_asana/streams/portfolios.py
> +def get_portfolies_for_workspace(workspace_id, owner, opt_fields):
Add function comment here and above.

2021-10-29 06:50 UTC, dbshah1212 commented on tap_asana/streams/sections.py
> +def get_sections_for_projects(project_gid, owner, opt_fields):
Add function comment

2021-10-29 06:51 UTC, dbshah1212 commented on tap_asana/streams/stories.py
> +def get_stories_for_tasks(task_gid, opt_fields):
Add function comment

2021-10-29 06:51 UTC, dbshah1212 commented on tap_asana/streams/teams.py
> +def get_users_for_teams(team):
Add function comments, here and above

2021-10-29 07:22 UTC, savan-chovatiya commented on tap_asana/streams/base.py
> +        return data
Added above comments as a code comment.

2021-10-29 07:23 UTC, savan-chovatiya commented on tap_asana/streams/portfolios.py
> +def get_portfolies_for_workspace(workspace_id, owner, opt_fields):
Added comments for both of the functions.

2021-10-29 07:23 UTC, savan-chovatiya commented on tap_asana/streams/sections.py
> +def get_sections_for_projects(project_gid, owner, opt_fields):
Added comments for the function.

2021-10-29 07:23 UTC, savan-chovatiya commented on tap_asana/streams/stories.py
> +def get_stories_for_tasks(task_gid, opt_fields):
Added comments for the function.

2021-10-29 07:23 UTC, savan-chovatiya commented on tap_asana/streams/teams.py
> +def get_users_for_teams(team):
Added comments for both of the functions.

2021-12-09 12:01 UTC, karanpanchal-crest approved these changes

2021-12-10 17:44 UTC, KrisPersonal requested changes
What is the purpose of start_date within asana.py __init__? It is not being used at all
def __init__(self, client_id, client_secret, redirect_uri, refresh_token, start_date, access_token=None):

2021-12-10 17:58 UTC, KrisPersonal commented on tap_asana/streams/base.py
>  from singer.messages import StateMessage
In the above code of imports, I see datetime , import time. Where is this being used in the code? If not, remove the imports

2021-12-13 05:59 UTC, harshpatel4crest commented
@KrisPersonal The start date in the **asana.py** is not used and the datetime and time imports in the **base.py** are also not used.
As part of PR #39, we have already removed the unused imports and **start_date** from the **init** function of **asana.py** file as we have also added pylint in the tap.

2021-12-13 21:07 UTC, kspeer825 approved these changes

2021-12-13 22:25 UTC, KrisPersonal approved these changes

2021-12-13 22:26 UTC, KrisPersonal commented on tap_asana/streams/base.py
> +        return data
@savan-chovatiya By making it as a list, will this have memory issue later on?

2021-12-14 11:53 UTC, savan-chovatiya commented on tap_asana/streams/base.py
> +        return data
No, list typecast can cause MemoyError but we already removed that code after we got the solution from Dan and this code is outdated so no list typecast In code-changes now.

2021-12-21 03:39 UTC, merged