TDL-20794: Upgrade SDK Version and add missing fields.
singer-io/tap-asana pull request #48
Opened 2022-10-10 04:50 UTC by harshpatel4crest

# Description of change
TDL-20794: Upgrade SDK Version and add missing fields.
- Upgraded the python-asana SDK version to **1.0.0**
- Added missing fields in the schema as per the Stability Analysis.

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-10-11 13:31 UTC, dbshah1212 commented on tap_asana/schemas/projects.json
> +        "object"
Any reason for changing the type? It will lead to a Major release.

2022-10-12 05:21 UTC, harshpatel4crest commented on tap_asana/schemas/projects.json
> +        "object"
Reverted the updating of datatype.

2022-10-12 06:53 UTC, savan-chovatiya approved these changes

2022-10-12 11:57 UTC, dbshah1212 approved these changes

2023-01-05 21:17 UTC, TaylorFacen-AL commented
Looks like this PR added in a section column for the tasks table. Any idea on when this can get merged in @hpatel41 @dbshah1212 @savan-chovatiya ?

2023-01-16 10:48 UTC, RushiT0122 requested changes

2023-01-16 10:48 UTC, RushiT0122 commented on setup.py
> +        "asana==1.0.0",
Latest `SDK version 3.0.0` is available.

2023-01-16 10:48 UTC, RushiT0122 commented on setup.py
>          'singer-python==5.12.2'
Latest `singer-python version 5.13.0` available

2023-01-16 10:50 UTC, RushiT0122 approved these changes

2023-01-16 14:15 UTC, rdeshmukh15 commented
Change the `Description of change` for this PR

2023-01-16 14:20 UTC, rdeshmukh15 commented on tap_asana/schemas/portfolios.json
> +                  }
Mention the format for these fields

2023-01-16 14:22 UTC, rdeshmukh15 commented on tap_asana/schemas/portfolios.json
> +              }
Mention the date-time format here too

2023-01-16 14:25 UTC, rdeshmukh15 commented on tap_asana/schemas/projects.json
> +              }
Add the date-time format wherever required

2023-01-16 15:03 UTC, rdeshmukh15 reviewed
Add the new fields introduced as per the stability analysis

2023-01-17 05:36 UTC, rdeshmukh15 commented
If possible can you please fetch `fields` list dynamically(i.e. from the catalog)  instead of hardcoding as defined in every file of streams.

2023-01-27 13:10 UTC, rdeshmukh15 commented on tap_asana/schemas/portfolios.json
> +                  }
As per the documentation, it is supposed to be the date and date_time with string datatype and hence, not added the format but can add the format date-time for field due_on

2023-01-27 13:16 UTC, rdeshmukh15 commented on tap_asana/schemas/projects.json
> +              }
As per the documentation, it is supposed to be the date and date_time with string datatype and hence, not added the format but can add the format date-time for fields due_on and due_date

2023-01-31 13:21 UTC, nitingaikwad1 approved these changes

2023-01-31 13:58 UTC, kethan1122 approved these changes

2023-02-14 13:52 UTC, merged